version: 2.1
           
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |   
            cd ~/project/frontend && npm i         
            npm run build           
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |      
             cd ~/project/backend && npm i               
             npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  test-frontend: 
    docker:
      # Docker image here
      - image: circleci/node:13.8.0
    steps:
      # Checkout code from git
      - checkout
      # Restore from cache
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      # Your job code here
      - run:
          name: Run tests with JUnit as reporter
          command: | 
            cd ~/project/frontend && npm i  
            npm run test
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/

  test-backend:
    docker:
      # Docker image here
      - image: circleci/node:13.8.0
    steps:
      # Checkout code from git
      - checkout
      # Restore from cache
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      # Your job code here
      - run:
          name: Run tests with JUnit as reporter
          command: |  
            cd ~/project/backend && npm i  
            npm run test
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
  
  scan-frontend:
    docker:
      # Docker image here
      - image: circleci/node:13.8.0
    steps:
      # Checkout code from git
      - checkout
      # Restore from cache
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      # Your job code here
      - run:
          name: Run frontend scan
          command: |  
            cd ~/project/backend && npm i  
            npm audit --audit-level=critical

  scan-backend:
    docker:
      # Docker image here
      - image: circleci/node:13.8.0
    steps:
      # Checkout code from git
      - checkout
      # Restore from cache
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      # Your job code here
      - run:
          name: Run backend scan
          command: |  
            cd ~/project/backend && npm i  
            npm audit --audit-level=critical

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
      - scan-backend:
          requires: [build-backend]
      